<?php
/**
 * Its api for config
 *
 * @since: 12/07/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Api\V1
 */

namespace VitePos\Api\V1;

use VitePos\Libs\API_Base;
use VitePos\Modules\POS_Settings;

/**
 * Class Pos_Api_Config
 *
 * @package VitePos\Api\V1
 */
class Pos_Api_Config extends API_Base {

	/**
	 * The set api base is generated by appsbd
	 *
	 * @return mixed|string
	 */
	public function set_api_base() {
		return 'basic';
	}

	/**
	 * The routes is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function routes() {
		$this->register_rest_route( 'GET', 'settings', array( $this, 'basic_settings' ) );
		$this->register_rest_route( 'GET', 'test', array( $this, 'test_cache' ) );
		$this->register_rest_route( 'GET', 'countries', array( $this, 'country_list' ) );
	}
	/**
	 * The set route permission is generated by appsbd
	 *
	 * @param \VitePos\Libs\any $route Its string.
	 *
	 * @return bool
	 */
	public function set_route_permission( $route ) {
		return true;
	}

	/**
	 * The basic settings is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function basic_settings() {
		$resdata           = new \stdClass();
		$resdata->settings = POS_Settings::get_settings();
		$this->response->set_response( true, '', $resdata );
		return $this->response->get_response();
	}
	/**
	 * The basic settings is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function test_cache() {
		$resdata           = new \stdClass();
		$resdata->time = date('Y-m-d h:i:s A');
		$this->response->set_response( true, '', $resdata );
		return $resdata;
	}
	/**
	 * The basic settings is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function country_list() {
		$this->response->set_response( true, '', POS_Settings::get_module_instance()->get_countries() );
		return $this->response;
	}

}
